Repository chanzuckerberg/idseq-web, pull requests merged in 2020-05, with the labels that each got.

#3298 Fix bug with admin-only metadata auto-populate.
  app/assets/src/components/common/MetadataManualInput.jsx
Labels: skip qa: no UX impact

#3295 Update phage list
  app/helpers/taxon_lineage_helper.rb
Labels: bot/merge, skip qa: no UX impact

#3301 IDSEQ-2401: Make taxon_blacklist a var of alignment_config
  app/lib/dags/non_host_alignment.json.jbuilder
  app/lib/dags/postprocess.json.jbuilder
  app/models/alignment_config.rb
  app/models/pipeline_run_stage.rb
  db/migrate/20200424214217_add_s3_taxon_blacklist_path_to_alignment_config.rb
  db/schema.rb
  lib/tasks/create_alignment_config.rake
  lib/tasks/load_blacklist.rake
Labels: bot/merge, skip qa: no UX impact

#3348 [IDSEQ-2510] The metadata filtering and info buttons are confusing when you're on the visualization tab
  app/assets/src/components/views/discovery/DiscoveryHeader.jsx
  app/assets/src/components/views/discovery/discovery_header.scss
Labels: ui-bug
