Repository chanzuckerberg/idseq-web, pull requests merged in 2020-06, with the labels that each got.

#3368 Update rails gem to 5.2.4.3 for security advisories
  Gemfile.lock
Labels: skip qa: no UX impact

#3373 [Release Fix CP] Fix bug with missing nucleotide type (#3372)
  app/services/sfn_pipeline_dispatch_service.rb
Labels: bot/merge

#3381 IDSEQ-2526 - Allow deploy script to work in idseq-prod account
  bin/deploy
  bin/get_private_ip
  bin/shell
Labels: bot/merge

#3374 [IDSEQ-2769] Table headers overlap when the right side panel is opened or window size changes.
  app/assets/src/components/visualizations/table/BaseTable.jsx
Labels: ui-bug

#3384 [IDSEQ-2850] [Firefox] Scrolling creates large white gap in Heatmap between metadata and taxa rows
  app/assets/src/components/visualizations/heatmap/Heatmap.js
Labels: ui-bug
