Repository chanzuckerberg/idseq-web, pull requests merged in 2020-03, with the labels that each got.

#3124 [bug] PipelineRun Factory inconsistent behavior
  spec/factories/pipeline_runs.rb
Labels: bot/merge, skip qa

#3088 IDSEQ-2273: Change wording of "create a collection" to "create a background"
  app/assets/src/components/views/samples/CollectionModal.jsx
  app/assets/src/components/views/samples/SamplesView.jsx
  app/assets/src/components/views/samples/collection_modal.scss
Labels: bot/merge

#3119 Filter out user created host genomes from metadata dict
  app/assets/src/components/views/metadata/MetadataDictionary.jsx
Labels: bot/merge

#3129 [Release fix CP] Always hide additional output from host filtering (#3123)
  app/services/retrieve_pipeline_viz_graph_data_service.rb
Labels: bot/merge

#3128 [Release fix CP] Fix bulk download insert size metrics (#3127)
  app/helpers/samples_helper.rb
Labels: bot/merge

#3137 [Datadog] Include exception type in autoscaling update error logs
  app/jobs/autoscaling.py
Labels: bot/merge

#3136 Clarify ALIGNMENT_CONFIG_DEFAULT_NAME
  app/models/alignment_config.rb
  docker-compose.yml
Labels: skip qa, skip qa: no UX impact

#3142 Remove webtest from docker compose
  docker-compose.yml
Labels: skip qa, skip qa: no UX impact

#3116 IDSEQ-2278 - Update PipelineRunStage job_status for step function executions
  app/models/pipeline_run_stage.rb
  spec/models/pipeline_run_stage_spec.rb
Labels: bot/merge

#3113 Refactor dag json generation and stage batch job trigger
  app/helpers/pipeline_runs_helper.rb
  app/models/pipeline_run_stage.rb
Labels: bot/merge

#3144 Fix bug in Institution user field
  app/assets/src/components/CreateUser.jsx
Labels: bot/merge

#3134 Fix issue with jq on linux
  bin/deploy_automation/_shared_functions.sh
Labels: bot/merge

#3159 [Release fix] Save dag json to pipeline run stage. (#3158)
  app/models/pipeline_run_stage.rb
Labels: bot/merge

#3157 IDSEQ-2311: Remove Min Contigs Reads filter from report page
  app/assets/src/components/PipelineSampleReport.jsx
  app/assets/src/components/views/SampleViewV2/ReportFilters.jsx
  app/assets/src/components/views/report/filters/MinContigReadsFilter.jsx
  app/assets/src/components/views/report/filters/min_contig_reads_filter.scss
Labels: bot/merge

#3152 [IDSEQ-2192 ] [Heatmap] Append sample ids to samples with duplicate names
  app/assets/src/components/common/Heatmap/MetadataLegend.jsx
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapView.jsx
  app/assets/src/components/views/compare/SamplesHeatmapVis.jsx
  app/assets/src/components/visualizations/heatmap/Heatmap.js
Labels: bot/merge

#3162 Avoid rails cache in mass validation
  app/models/application_record.rb
Labels: bot/merge

#3163 [IDSEQ-2171] [Heatmap] Show notification for failed/waiting samples
  app/assets/src/api/bulk_downloads.js
  app/assets/src/components/layout/Accordion.jsx
  app/assets/src/components/layout/accordion.scss
  app/assets/src/components/ui/notifications/AccordionNotification.jsx
  app/assets/src/components/ui/notifications/accordion_notification.scss
  app/assets/src/components/ui/notifications/notification.scss
  app/assets/src/components/views/bulk_download/BulkDownloadModal.jsx
  app/assets/src/components/views/bulk_download/bulk_download_modal_footer.scss
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapView.jsx
  app/assets/src/components/views/compare/SamplesHeatmapView/samples_heatmap_view.scss
  app/assets/src/styles/themes/_typography.scss
Labels: bot/merge

#3167 [release fix] Fix logic of mass_validation_enabled class var
  app/models/application_record.rb
Labels: skip qa: no UX impact

#3166 Fix logic of mass_validation_enabled class var
  app/models/application_record.rb
Labels: skip qa: no UX impact

#3168 Add font-caps mixins to playground
  app/assets/src/components/views/playgrounds/playground_typography.scss
Labels: bot/merge, skip qa: no UX impact

#3171 Fix sfn_info error undefined method
  app/helpers/pipeline_runs_helper.rb
  spec/helpers/pipeline_runs_helper_spec.rb
Labels: bot/merge

#3173 [release fix] Remove table exists call
  app/models/application_record.rb
Labels: bot/merge

#3175 Handle duplicate sample names in AMR Heatmap
  app/assets/src/components/views/amr_heatmap/AMRHeatmapView.jsx
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapView.jsx
Labels: bot/merge

#3169 Clean up unneeded contig code
  app/assets/src/components/views/SampleViewV2/ReportTable.jsx
  app/assets/src/components/views/SampleViewV2/SampleViewHeader.jsx
  app/assets/src/components/views/SampleViewV2/SampleViewV2.jsx
  app/services/pipeline_report_service.rb
Labels: bot/merge

#3179 Fix unknown firstpos: NilClass bug in development.
  config/initializers/routes.rb
Labels: skip qa: no UX impact

#3177 Apply correct fix to validation guard
  app/models/application_record.rb
Labels: bot/merge

#3180 Remove validates_associated from PipelineRun
  app/models/pipeline_run.rb
Labels: bot/merge

#3183 Add launched features
  app/helpers/app_config_helper.rb
  app/models/app_config.rb
  app/models/user.rb
  lib/tasks/features.rake
  spec/models/user_spec.rb
Labels: bot/merge

#3188 [Release fix CP] [Heatmap] Fix bug with multiple duplicate sample names on heatmaps
  app/assets/src/components/views/amr_heatmap/AMRHeatmapView.jsx
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapView.jsx
Labels: bot/merge

#3182 Add error message when bulk download creation fails unexpectedly.
  app/assets/src/components/views/bulk_download/BulkDownloadModal.jsx
Labels: bot/merge

#3195 Log and notify if more than 100 samples uploaded at once
  app/controllers/samples_controller.rb
  app/models/project.rb
Labels: bot/merge

#3192 Handle error in kickoff_pipeline
  app/controllers/samples_controller.rb
  app/models/sample.rb
Labels: bot/merge, skip qa: guarded feature

#3148 IDSEQ-1398: Ensure required metadata fields (and host defaults) are associated with all host genomes
  app/models/host_genome.rb
  app/models/metadata_field.rb
  spec/factories/host_genomes.rb
  spec/factories/samples.rb
  spec/factories/users.rb
  spec/helpers/bulk_download_helper_spec.rb
  spec/helpers/samples_helper_spec.rb
  spec/models/host_genome_spec.rb
  spec/models/metadata_field_spec.rb
  spec/requests/sample_request_spec.rb
Labels: bot/merge, skip qa: no UX impact

#3191 Correct output states validation
  app/models/output_state.rb
Labels: bot/merge

#3194 [IDSEQ-2414] [Heatmap filtering] Add explanatory text for heatmap data
  app/assets/src/components/ui/containers/ColumnHeaderTooltip.jsx
  app/assets/src/components/ui/icons/SmallInfoIcon.jsx
  app/assets/src/components/ui/icons/index.js
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapControls.jsx
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapView.jsx
  app/assets/src/components/views/compare/SamplesHeatmapView/samples_heatmap_view.scss
  app/controllers/visualizations_controller.rb
Labels: bot/merge

#3197 IDSEQ-2364 - Async pipeline notification service
  app/models/pipeline_run.rb
  app/services/update_pipeline_run_stage_service.rb
  spec/models/pipeline_run_spec.rb
  spec/services/update_pipeline_run_stage_service_spec.rb
  spec/spec_helper.rb
Labels: bot/merge

#3199 Add admin upload options.
  app/assets/src/api/upload.js
  app/assets/src/components/common/CoverageVizBottomSidebar/CoverageVizBottomSidebar.jsx
  app/assets/src/components/common/CoverageVizBottomSidebar/coverage_viz_bottom_sidebar.scss
  app/assets/src/components/ui/containers/HelpIcon.jsx
  app/assets/src/components/ui/containers/help_icon.scss
  app/assets/src/components/views/SampleUploadFlow/AdminUploadOptions.jsx
  app/assets/src/components/views/SampleUploadFlow/ReviewStep.jsx
  app/assets/src/components/views/SampleUploadFlow/UploadProgressModal.jsx
  app/assets/src/components/views/SampleUploadFlow/admin_upload_options.scss
  app/controllers/samples_controller.rb
Labels: bot/merge

#3201 IDSEQ-2490: Fix new host bug on csv upload
  app/assets/src/components/common/MetadataUpload.jsx
  app/assets/src/components/views/SampleUploadFlow/UploadMetadataStep.jsx
Labels: bot/merge

#3203 [Release Fix CP] Add OuputPrefix to SFN dispatch call
  app/services/sfn_pipeline_dispatch_service.rb
  spec/services/sfn_pipeline_dispatch_service_spec.rb
Labels: bot/merge

#3208 Add customizable subsampling parameters for specified projects.
  app/controllers/samples_controller.rb
  app/models/app_config.rb
  spec/requests/sample_request_spec.rb
  test/controllers/backgrounds_controller_test.rb
Labels: skip qa: no UX impact

#3219 Remove bulk download feature flag.
  app/assets/src/components/common/Header.jsx
  app/assets/src/components/ui/controls/dropdowns/DownloadIconDropdown.jsx
  app/assets/src/components/ui/controls/dropdowns/index.js
  app/assets/src/components/views/samples/ReportsDownloader.js
  app/assets/src/components/views/samples/SamplesView.jsx
  app/controllers/bulk_downloads_controller.rb
  spec/controllers/benchmarks_controller_spec.rb
  spec/controllers/bulk_downloads_controller_spec.rb
  spec/controllers/user_settings_controller_spec.rb
Labels: bot/merge

#3213 [IDSEQ-2411] [Heatmap filtering] Refactor background filter to load less data
  app/assets/src/api/index.js
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapControls.jsx
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapView.jsx
  app/controllers/visualizations_controller.rb
  app/helpers/heatmap_helper.rb
  config/routes.rb
Labels: bot/merge

#3224 [IDSEQ-2422] [Heatmap] Add hover effects to rows and columns
  app/assets/src/components/visualizations/heatmap/Heatmap.js
Labels: bot/merge

#3215 Move taxon whitelisting to taxon count method of idseq-dag
  app/lib/dags/postprocess.json.jbuilder
  app/models/pipeline_run_stage.rb
Labels: bot/merge

#3226 [Release fix] Move taxon whitelisting to taxon count method of idseq-dag
  app/lib/dags/postprocess.json.jbuilder
  app/models/pipeline_run_stage.rb
Labels: skip qa: no UX impact

#3217 Fix analytics call for bulk download notification.
  app/assets/src/components/views/bulk_download/BulkDownloadNotification.jsx
Labels: bot/merge, skip qa: no UX impact

#3220 Remove legacy upload page.
  app/assets/src/api/index.js
  app/assets/src/api/upload.js
  app/assets/src/components/BulkUploadImport.jsx
  app/assets/src/components/SampleUpload.jsx
  app/assets/src/components/ui/controls/UploadBox.jsx
  app/assets/src/components/ui/icons/BeeIcon.jsx
  app/assets/src/components/ui/icons/CatIcon.jsx
  app/assets/src/components/ui/icons/ERCCIcon.jsx
  app/assets/src/components/ui/icons/HumanIcon.jsx
  app/assets/src/components/ui/icons/MosquitoIcon.jsx
  app/assets/src/components/ui/icons/MouseIcon.jsx
  app/assets/src/components/ui/icons/PigIcon.jsx
  app/assets/src/components/ui/icons/TickIcon.jsx
  app/assets/src/components/ui/icons/WormIcon.jsx
  app/assets/src/components/ui/icons/index.js
  app/assets/src/components/utils/links.js
  app/assets/src/components/utils/sample.js
  app/assets/src/components/views/BulkUploadimportPage/BulkUploadImportPage.jsx
  app/assets/src/components/views/BulkUploadimportPage/index.js
  app/assets/src/helpers/ObjectHelper.js
  app/assets/src/helpers/url.js
  app/assets/src/index.jsx
  app/assets/src/styles/_header.scss
  app/controllers/samples_controller.rb
  app/views/samples/bulk_new.html.erb
  app/views/samples/new.html.erb
  config/routes.rb
  test/controllers/power_controller_test.rb
  test/controllers/samples_controller_test.rb
Labels: bot/merge

#3227 Add local test coverage calculation
  .simplecov
  Gemfile
  Gemfile.lock
  package-lock.json
  package.json
  spec/spec_helper.rb
  test/test_helper.rb
Labels: skip qa: no UX impact

#3204 Update npm packages and json due to security alerts
  .eslintrc
  Gemfile
  Gemfile.lock
  package-lock.json
  package.json
  webpack.config.common.js
Labels: skip qa: regression test

#3234 Update sensitive NPM packages
  .eslintrc
  package-lock.json
  package.json
  webpack.config.common.js
Labels: bot/merge, skip qa: regression test

#3229 [IDSEQ-2425] [IDSEQ-2413] Allow users to add taxon to heatmap
  app/assets/src/components/common/Heatmap/TaxonSelector.jsx
  app/assets/src/components/ui/controls/SearchBoxList.jsx
  app/assets/src/components/ui/controls/search_box_list.scss
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapView.jsx
  app/assets/src/components/views/compare/SamplesHeatmapVis.jsx
  app/assets/src/components/visualizations/heatmap/Heatmap.js
  app/assets/src/components/visualizations/heatmap/heatmap.scss
Labels: bot/merge, skip qa: guarded feature
