Repository chanzuckerberg/idseq-web, pull requests merged in 2020-04, with the labels that each got.

#3238 [IDSEQ-2426] Trigger hover effect when taxon is added to heatmap
  app/assets/src/components/views/compare/SamplesHeatmapView/SamplesHeatmapView.jsx
  app/assets/src/components/views/compare/SamplesHeatmapVis.jsx
  app/assets/src/components/visualizations/heatmap/Heatmap.js
Labels: bot/merge, skip qa: guarded feature

#3243 [release fix] Fix contig threshold filters
  app/assets/src/components/views/SampleViewV2/SampleViewV2.jsx
  app/assets/src/components/views/SampleViewV2/constants.js
Labels: bot/merge

#3240 IDSEQ-2517: Fix contig count bug in CSV download of report
  app/controllers/samples_controller.rb
  app/models/pipeline_run.rb
  app/services/pipeline_report_service.rb
  spec/factories/pipeline_runs.rb
  spec/services/pipeline_report_service_spec.rb
Labels: bot/merge

#3231 IDSEQ-2514: Update DCR tooltip
  app/assets/src/components/views/samples/constants.js
Labels: bot/merge

#3242 IDSEQ-2603: Fix contig threshold filters
  app/assets/src/components/views/SampleViewV2/SampleViewV2.jsx
  app/assets/src/components/views/SampleViewV2/constants.js
Labels: bot/merge

#3254 Add new info for nonhost fastq step
  app/lib/dags/experimental.json.jbuilder
  app/models/pipeline_run_stage.rb
  lib/tasks/export_dags.rake
Labels: bot/merge

#3246 Add to pipeline_runs a link to batch job page and batch job exit reason
  app/lib/aws_util.rb
  app/models/pipeline_run_stage.rb
  app/views/samples/pipeline_runs.html.erb
Labels: bot/merge

#3262 Fixes for interaction with the new SFN pipeline
  app/models/pipeline_run.rb
  app/services/sfn_pipeline_dispatch_service.rb
Labels: skip qa: guarded feature

#3260 IDSEQ-2635 IDSEQ-2641 Fix bugs with location metadata auto-adjusting.
  app/assets/src/components/common/MetadataCSVLocationsMenu.jsx
  app/assets/src/components/common/MetadataUpload.jsx
  app/assets/src/components/ui/controls/GeoSearchInputBox.jsx
  app/helpers/error_helper.rb
  app/models/location.rb
  app/models/metadatum.rb
  spec/factories/host_genomes.rb
  spec/factories/locations.rb
  spec/factories/samples.rb
  spec/models/location_spec.rb
  spec/models/metadata_spec.rb
  test/models/location_test.rb
Labels: bot/merge

#3267 [Release fix CP] Added staging deployment environment to map (#3266)
  app/services/sfn_pipeline_dispatch_service.rb
Labels: bot/merge

#3274 [Release fix] Use require to load PipelineRunStage constants (#3270)
  db/migrate/20200414220332_rename_alignment.rb
Labels: bot/merge

#3275 [Release fix] Raw sql migration (#3272)
  db/migrate/20200414220332_rename_alignment.rb
Labels: bot/merge

#3281 Remove [Datadog] from logs
  app/controllers/samples_controller.rb
  app/jobs/compute_background.rb
  app/jobs/result_monitor_loader.rb
  app/models/phylo_tree.rb
  app/models/pipeline_run.rb
  app/models/sample.rb
  lib/tasks/result_monitor.rake
Labels: bot/merge

#3283 Rake task to create a load test
  lib/tasks/load_test.rake
Labels: bot/merge

#3282 Update icon playground with recent icons.
  app/assets/src/components/ui/icons/index.js
  app/assets/src/components/views/playgrounds/playground_icons.scss
Labels: skip qa: no UX impact

#3293 Remove alignment chunk columns
  db/migrate/20200422181622_remove_chunk_counts_from_pipeline_runs.rb
  db/schema.rb
Labels: skip qa: no UX impact
